version: 2
jobs:
  build:

    working_directory: ~/circlesonar

    docker:
      - image: circleci/openjdk:8u171-jdk

    steps:

      - checkout

      - restore_cache:
          key: circlesonar-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circlesonar-{{ checksum "pom.xml" }}

      - run:
          command: |
            echo Running tests
            mvn clean test
            echo Publishing results to sonar
            mvn sonar:sonar \
              -Dsonar.projectKey=colorcodecanvas_circlesonar \
              -Dsonar.organization=colorcodecanvas \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=218a21bec532782bc07312d4ff869ea329e21171

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/circlesonar.jar