version: 2
jobs:
  build:
    working_directory: ~/circlesonar
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - restore_cache:
          key: circlesonar-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circlesonar-{{ checksum "pom.xml" }}
      - run:
          command: |
            echo Running tests
            set +e
            mvn clean test
      - run: .circleci/sonar_publisher.sh


